import type { OpsPlan } from "../lib/types";
import { SourceBadge } from "./SourceBadge";

export function RiskPlanPanel({ plan }: { plan?: OpsPlan }) {
  const levelColor =
    plan?.riskLevel === "critical"
      ? "from-command-red to-command-amber"
      : plan?.riskLevel === "high"
      ? "from-command-amber to-command-red"
      : "from-command-green to-command-cyan";

  return (
    <section className="relative rounded-[2rem] border border-slate-200 bg-white p-6 shadow-[0_24px_80px_rgba(15,23,42,0.10)] md:p-8">
      <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-amber-100 blur-3xl" />
      <div className="relative mb-6 flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
        <div className="min-w-0">
          <p className="text-xs font-bold uppercase tracking-[0.24em] text-emerald-700">Nebius Risk Plan</p>
          <h2 className="mt-2 break-words text-4xl font-black tracking-tight text-slate-950 md:text-5xl">
            {plan ? `${plan.riskLevel.toUpperCase()} ${plan.riskScore}/100` : "Awaiting Analysis"}
          </h2>
          <p className="text-pretty mt-3 max-w-3xl leading-7 text-slate-600">
            {plan ? plan.summary : "Run the demo to produce a grounded operational plan from live signals, Butterbase RAG, Evermind memory, and Nebius inference."}
          </p>
        </div>
        <div className="min-w-56 rounded-3xl border border-slate-200 bg-slate-50 p-4">
          <p className="text-xs font-bold uppercase tracking-[0.20em] text-slate-500">Risk Meter</p>
          <div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-200">
            <div className={`h-full rounded-full bg-gradient-to-r ${levelColor}`} style={{ width: `${plan?.riskScore ?? 12}%` }} />
          </div>
          <p className="mt-3 text-xs leading-5 text-slate-500">Generated by Nebius. Grounded by retrieved context.</p>
        </div>
      </div>

      {plan ? (
        <div className="relative space-y-6">
          <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
            <h3 className="mb-3 text-sm font-bold uppercase tracking-[0.22em] text-slate-400">Why This Matters</h3>
            <ul className="grid gap-3 md:grid-cols-2">
              {plan.reasoning.map((reason, index) => (
                <li key={reason} className="flex min-w-0 gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-sm leading-6 text-slate-600 shadow-sm">
                  <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-xs font-bold text-emerald-700">
                    {index + 1}
                  </span>
                  <span className="text-pretty min-w-0 break-words">{reason}</span>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <h3 className="mb-3 text-sm font-bold uppercase tracking-[0.22em] text-slate-400">Recommended Actions</h3>
            <div className="grid items-stretch gap-4 lg:grid-cols-3">
              {plan.recommendedActions.map((action, index) => (
                <div key={action.id} className="group min-w-0 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-xl">
                  <div className="mb-4 flex items-start justify-between gap-3">
                    <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-2xl bg-slate-950 text-sm font-black text-white">
                      {index + 1}
                    </span>
                    <span className="whitespace-normal rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-right text-[10px] font-bold uppercase tracking-wide text-amber-700">{action.urgency.replaceAll("_", " ")}</span>
                  </div>
                  <p className="text-pretty break-words text-base font-bold leading-6 text-slate-950">{action.title}</p>
                  <p className="text-pretty mt-2 break-words text-sm leading-6 text-slate-600">{action.rationale}</p>
                  <div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs text-slate-500">
                    <span>Owner</span>
                    <span className="break-words text-right font-semibold text-slate-800">{action.owner}</span>
                  </div>
                  <div className="mt-3 flex flex-wrap gap-2">
                    {action.sourceBasis.map((source) => (
                      <SourceBadge key={source} source={source} />
                    ))}
                    <SourceBadge source="nebius_inference" />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      ) : (
        <p className="text-slate-400">Run the demo analysis to collect signals, retrieve policies and memories, and generate a structured plan.</p>
      )}
    </section>
  );
}
