import type { OpsPlan } from "../lib/types";
import { ActionCard } from "./ActionCard";

function scoreTone(level?: string) {
  if (level === "critical") return "from-red-500 to-amber-400";
  if (level === "high") return "from-orange-500 to-red-500";
  if (level === "medium") return "from-amber-400 to-cyan-400";
  return "from-emerald-400 to-cyan-400";
}

export function RiskPlanHero({ plan, running }: { plan?: OpsPlan; running: boolean }) {
  const width = `${plan?.riskScore ?? (running ? 48 : 8)}%`;

  return (
    <section className="relative flex min-h-[520px] flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white p-5 shadow-2xl shadow-slate-900/10">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_15%_10%,rgba(14,165,233,0.12),transparent_30%),radial-gradient(circle_at_85%_0%,rgba(124,58,237,0.10),transparent_28%)]" />
      <div className="relative flex items-start justify-between gap-4">
        <div>
          <p className="text-sm font-bold text-sky-700">Nebius Risk Plan</p>
          <p className="mt-1 text-sm text-slate-500">Generated by Nebius · Grounded by Butterbase RAG + Evermind memory</p>
        </div>
        <span className="rounded-full border border-sky-200 bg-sky-50 px-3 py-1 text-xs font-bold text-sky-700">
          AI plan
        </span>
      </div>

      {!plan ? (
        <div className="relative flex flex-1 items-center justify-center py-12">
          <div className="max-w-md text-center">
            <div className="mx-auto mb-5 h-16 w-16 rounded-3xl border border-slate-200 bg-slate-50 shadow-inner" />
            <h2 className="text-3xl font-black tracking-tight text-slate-950">{running ? "Generating risk plan" : "Awaiting analysis"}</h2>
            <p className="mt-3 text-pretty text-sm leading-6 text-slate-500">
              {running
                ? "CrowdOps is retrieving context and asking Nebius for a structured operating plan."
                : "Start the match-day analysis to turn live signals into an approved operating plan."}
            </p>
            <div className="mt-6 h-2 overflow-hidden rounded-full bg-slate-100">
              <div className="h-full animate-pulse rounded-full bg-gradient-to-r from-sky-500 to-violet-500" style={{ width }} />
            </div>
          </div>
        </div>
      ) : (
        <div className="relative mt-6 flex flex-1 flex-col gap-5">
          <div className="grid gap-5 lg:grid-cols-[0.7fr_1.3fr]">
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
              <p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Risk Score</p>
              <div className="mt-4 flex items-end gap-3">
                <span className="text-5xl font-black tracking-tight text-slate-950">{plan.riskLevel.toUpperCase()}</span>
              </div>
              <div className="mt-2 text-4xl font-black text-slate-800">{plan.riskScore}/100</div>
              <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-200">
                <div className={`h-full rounded-full bg-gradient-to-r ${scoreTone(plan.riskLevel)}`} style={{ width }} />
              </div>
            </div>

            <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
              <h3 className="text-lg font-extrabold text-slate-950">{plan.summary}</h3>
              <ul className="mt-4 grid gap-2 md:grid-cols-2">
                {plan.reasoning.slice(0, 6).map((reason) => (
                  <li key={reason} className="flex gap-2 rounded-2xl bg-slate-50 p-3 text-sm leading-5 text-slate-600">
                    <span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-sky-500" />
                    <span className="text-pretty">{reason}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div>
            <div className="mb-3 flex items-center justify-between">
              <h3 className="text-sm font-bold uppercase tracking-[0.14em] text-slate-500">Recommended Actions</h3>
              <p className="text-xs text-slate-500">{plan.recommendedActions.length} actions</p>
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              {plan.recommendedActions.map((action, index) => (
                <ActionCard key={action.id} action={action} index={index} />
              ))}
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
